version: '1.0'
name: branch-pipeline
displayName: BranchPipeline
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - main
stages:
  - name: compile
    displayName: 编译
    strategy: naturally
    trigger: auto
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 14.16.0
        commands:
          - npm install -g pnpm@8.6.1
          - pnpm install
          - ''
          - if [ -d "docs/.vuepress/dist" ]; then
          - '  rm -rf docs/.vuepress/dist'
          - fi
          - ''
          - echo '🚀 开始构建...'
          - ''
          - 'npm run build:docs # > /dev/null 2>&1'
          - ''
          - if [ $? -ne 0 ]; then
          - '    echo "❌ 构建失败。请使用 npm run build:docs 命令构建以查看详情"'
          - '    exit'
          - fi
          - ''
          - echo '🎉 构建成功!'
          - ''
          - echo '开始将生成的静态网站推送至 gt-pages 分支'
          - ''
          - cd docs/.vuepress/dist && git init  && git checkout --orphan gt-pages  \
          - '&& git add .  && git commit -m "pushed by deploy.sh"  \'
          - '&& git remote add origin git@gitee.com:vingogo/vin-ui.git  \'
          - '&& git push origin gt-pages --force  && rm -rf .git'
          - ''
          - if [ $? -ne 0 ]; then
          - '    echo "❌ 抱歉，推送失败了"'
          - '    exit'
          - fi
          - ''
          - echo '🎉 推送成功!'
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./docs/.vuepress/dist
        caches: []
        strategy: {}
